// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts"
// @generated from file task/v1/task.proto (package task.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateTaskRequest, CreateTaskResponse, ListTasksRequest, ListTasksResponse, UpdateTaskStatusRequest, UpdateTaskStatusResponse } from "./task_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service task.v1.TaskService
 */
export const TaskService = {
  typeName: "task.v1.TaskService",
  methods: {
    /**
     * List tasks.
     *
     * @generated from rpc task.v1.TaskService.ListTasks
     */
    listTasks: {
      name: "ListTasks",
      I: ListTasksRequest,
      O: ListTasksResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Creates a task.
     *
     * @generated from rpc task.v1.TaskService.CreateTask
     */
    createTask: {
      name: "CreateTask",
      I: CreateTaskRequest,
      O: CreateTaskResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Updates a task's status.
     *
     * @generated from rpc task.v1.TaskService.UpdateTaskStatus
     */
    updateTaskStatus: {
      name: "UpdateTaskStatus",
      I: UpdateTaskStatusRequest,
      O: UpdateTaskStatusResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

